server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb+srv://dikkulah1:Logo@cluster0.dlrlm.mongodb.net/MovieAdvisor
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  main:
    allow-bean-definition-overriding: true