server:
  port: 8082
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:55000/payment
    username: root
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true